name: Statistics

on:
  workflow_dispatch:
    inputs:
      Config:
        description: The game configuration
        required: false
        default: |
          {
            "players": {
              "Exercise01AI": {},
              "Exercise02AI": {
                "search_depth": 3
              },
              "Exercise03AI": {
                "search_depth": 3
              },
              "Exercise04AI": {
                "search_depth": 3
              },
              "Exercise05AI": {
                "search_depth": 4
              },
              "Exercise06AI": {
                "search_depth": 4
              },
              "Exercise07AI": {
                "search_depth": 4
              },
              "Exercise08AI": {
                "search_depth": 4,
                "max_depth": 8
              },
              "StockfishPlayer": {
                "elo": 1500,
                "time_limit": 0.1
              }
            },
            "opponents": {
              "Exercise01AI": {},
              "Exercise02AI": {
                "search_depth": 3
              },
              "Exercise03AI": {
                "search_depth": 3
              },
              "Exercise04AI": {
                "search_depth": 3
              },
              "Exercise05AI": {
                "search_depth": 4
              },
              "Exercise06AI": {
                "search_depth": 4
              },
              "Exercise07AI": {
                "search_depth": 4
              },
              "Exercise08AI": {
                "search_depth": 4,
                "max_depth": 8
              },
              "StockfishPlayer": {
                "elo": 1500,
                "time_limit": 0.1
              }
            },
            "seed": 3,
            "repetitions": 3,
            "concurrent_games": 1,
            "exclude_reflexive_pairs": false,
            "make_symmetric_pairs": true
          }
      Filename:
        description: Name for the resulting .zip file
        required: false
        default: results

jobs:
  run_statistics:
    runs-on: ubuntu-latest

    env:
      STOCKFISH_VERSION: 14.1
      PYTHON_VERSION: 3.10.2

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache external libraries
        id: cache-libraries
        uses: actions/cache@v2
        with:
          path: lib/
          key: ${{ runner.os }}-lib

      - name: Fetch required libraries if no cache was found
        if: steps.cache-libraries.outputs.cache-hit != 'true'
        run: ./scripts/setup.sh

      - name: Install dependencies and convert notebooks
        run: |
          pip install notebook -r src/requirements.txt
          jupyter nbconvert --to python \
            --output-dir="python" \
            --TemplateExporter.extra_template_basedirs="scripts" \
            --template nbconverter_template \
            src/*.ipynb

      - name: Run statistics
        working-directory: python
        run: |
          echo "Running statistics"
          python Statistics.py
        env:
          config:  ${{  github.event.inputs.Config  }}

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{  github.event.inputs.Filename  }}
          path: |
            games/
            *.log
