name: Statistics

on:
  workflow_dispatch:
    inputs:
      Players:
        description: Array of players
        required: false
        default: >-
          Exercise01AI,
          Exercise02AI,
          Exercise03AI,
          Exercise04AI,
          Exercise05AI,
          Exercise06AI,
          Exercise07AI,
          StockfishPlayer
      Opponents:
        description: Array of opponents
        required: false
        default: >-
          Exercise01AI,
          Exercise02AI,
          Exercise03AI,
          Exercise04AI,
          Exercise05AI,
          Exercise06AI,
          Exercise07AI,
          StockfishPlayer
      Seed:
        description: Random seed
        required: false
        default: '3'
      Repetitions:
        description: Number of games per player pair
        required: false
        default: '5'
      Depth:
        description: Search depth for Minimax algorithm
        required: false
        default: '3'
      Filename:
        description: Name for the resulting .zip file
        required: false
        default: results

jobs:
  run_statistics:
    runs-on: ubuntu-latest

    env:
      STOCKFISH_VERSION: 14.1
      PYTHON_VERSION: 3.10.2

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache external libraries
        id: cache-libraries
        uses: actions/cache@v2
        with:
          path: lib/
          key: ${{ runner.os }}-lib

      - name: Fetch required libraries if no cache was found
        if: steps.cache-libraries.outputs.cache-hit != 'true'
        run: ./scripts/setup.sh

      - name: Run statistics notebook
        run: |
          pip install notebook -r src/requirements.txt
          echo "Running statistics notebook"
          ./scripts/nb_exec.sh src/Statistics.ipynb
        env:
          players:  ${{  github.event.inputs.Players  }}
          opponents:  ${{  github.event.inputs.Opponents  }}
          seed:  ${{  github.event.inputs.Seed  }}
          repetitions:  ${{  github.event.inputs.Repetitions  }}
          depth:  ${{  github.event.inputs.Depth  }}

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{  github.event.inputs.Filename  }}
          path: |
            games/
            *.log
