name: Testing

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
    paths:
        - 'src/**.ipynb'
  workflow_dispatch:

env:
  config: |
    {
      "players": [
        {
          "Exercise01AI": {}
        },
        {
          "Exercise02AI": {
            "search_depth": 3
          }
        },
        {
          "Exercise03AI": {
            "search_depth": 3
          }
        },
        {
          "Exercise04AI": {
            "search_depth": 3
          }
        },
        {
          "Exercise05AI": {
            "search_depth": 4
          }
        },
        {
          "Exercise06AI": {
            "search_depth": 4
          }
        },
        {
          "Exercise07AI": {
            "search_depth": 4
          }
        },
        {
          "Exercise08AI": {
            "search_depth": 4,
            "max_depth": 8
          }
        },
        {
          "StockfishPlayer": {
            "elo": 1500,
            "time_limit": 0.1
          }
        }
      ],
      "opponents": [
        {
          "Exercise01AI": {}
        },
        {
          "Exercise02AI": {
            "search_depth": 3
          }
        },
        {
          "Exercise03AI": {
            "search_depth": 3
          }
        },
        {
          "Exercise04AI": {
            "search_depth": 3
          }
        },
        {
          "Exercise05AI": {
            "search_depth": 4
          }
        },
        {
          "Exercise06AI": {
            "search_depth": 4
          }
        },
        {
          "Exercise07AI": {
            "search_depth": 4
          }
        },
        {
          "Exercise08AI": {
            "search_depth": 4,
            "max_depth": 8
          }
        },
        {
          "StockfishPlayer": {
            "elo": 1500,
            "time_limit": 0.1
          }
        }
      ],
      "seed": 0,
      "repetitions": 5,
      "concurrent_games": 1,
      "exclude_reflexive_pairs": false,
      "make_symmetric_pairs": true
    }

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      STOCKFISH_VERSION: 14.1
      PYTHON_VERSION: 3.10.2

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache external libraries
        id: cache-libraries
        uses: actions/cache@v2
        with:
          path: lib/
          key: ${{ runner.os }}-lib

      - name: Fetch required libraries if no cache was found
        if: steps.cache-libraries.outputs.cache-hit != 'true'
        run: ./scripts/setup.sh

      - name: Install dependencies and convert notebooks
        run: |
          pip install notebook -r src/requirements.txt
          jupyter nbconvert --to python \
            --output-dir="python" \
            --TemplateExporter.extra_template_basedirs="scripts" \
            --template nbconverter_template \
            src/*.ipynb

      - name: Run statistics
        working-directory: python
        run: |
          echo "Running statistics"
          python Statistics.py

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: |
            games/
            *.log
