name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - development
    paths:
      - '**.ipynb'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      STOCKFISH_VERSION: 14.1
      PYTHON_VERSION: 3.10.1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache external libraries
        id: cache-libraries
        uses: actions/cache@v2
        with:
          path: lib/
          key: ${{ runner.os }}-lib

      - name: Fetch required libraries if no cache was found
        if: steps.cache-libraries.outputs.cache-hit != 'true'
        run: |
          # Install stockfish
          stockfish=stockfish_${STOCKFISH_VERSION}_linux_x64
          wget https://stockfishchess.org/files/${stockfish}.zip
          unzip ${stockfish}.zip
          mv ${stockfish}/${stockfish} lib/stockfish/stockfish.exe
          chmod +x lib/stockfish/stockfish.exe

          # Fetch endgame library
          wget --execute="robots = off" --mirror --convert-links --no-parent http://tablebase.sesse.net/syzygy/3-4-5/
          mv tablebase.sesse.net/syzygy/3-4-5/*.{rtbz,rtbw,md5} lib/ending/3-4-5/
          cd lib/ending/3-4-5/ && md5sum -c checksum.md5

      - name: Run multiple Chess-AI games with different seeds
        run: |
          pip install notebook -r src/requirements.txt
          for seed in {1..42}; do
            echo "Running Chess-AI with seed ${seed}"
            CHESS_AI_SEED=$seed CHESS_AI_REPETITIONS=3 jupyter-execute src/Main.ipynb
          done

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: games/
